
GET  http://localhost:3000/cartoon HTTP/1.1

###

GET  http://localhost:3000/cartoon/1 HTTP/1.1

###

DELETE   http://localhost:3000/cartoon/2 HTTP/1.1


###

POST http://localhost:3000/cartoon HTTP/1.1
content-type: application/json

{
    "nome": "Testando novamente 22222222",
    "descricao": "21321321321",
    "foto": "231312321"
}
